apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hw-deployment 
spec: 
  replicas: 2   
  selector: 
    matchLabels: 
      app: hello-world 
  template: 
    metadata: 
      labels: 
        app: hello-world 
    spec: 
      containers: 
      - name: hw-container 
        image: bindugr/app3:latest  
        ports: 
        - containerPort: 5000
